version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "8000:8000"
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432"
volumes:
  postgres-data:
